
/* This file was generated automatically by Zephir do not modify it! */

#ifndef ZEPHIR_CLASS_ENTRIES_H
#define ZEPHIR_CLASS_ENTRIES_H

#include "yb/exception.zep.h"
#include "yb/view/viewinterface.zep.h"
#include "yb/factory/factoryinterface.zep.h"
#include "yb/logger/loggerbackendinterface.zep.h"
#include "yb/image/imageabstract.zep.h"
#include "yb/logger/loggerabstract.zep.h"
#include "yb/db/dbabstract.zep.h"
#include "yb/db/exception.zep.h"
#include "yb/loader/loaderabstract.zep.h"
#include "yb/task/taskmanagerabstract.zep.h"
#include "yb/upload/urigeneratorinterface.zep.h"
#include "yb/db/pdoabstract.zep.h"
#include "yb/di.zep.h"
#include "yb/factory/classnameabstract.zep.h"
#include "yb/image/image.zep.h"
#include "yb/image/imagebackendabstract.zep.h"
#include "yb/upload/storageabstract.zep.h"
#include "yb/application.zep.h"
#include "yb/db/collection.zep.h"
#include "yb/db/entity.zep.h"
#include "yb/db/model.zep.h"
#include "yb/db/pdomysql.zep.h"
#include "yb/db/queryexception.zep.h"
#include "yb/db/transactionexception.zep.h"
#include "yb/factory/exception.zep.h"
#include "yb/factory/factories.zep.h"
#include "yb/factory/namespaced.zep.h"
#include "yb/factory/shared.zep.h"
#include "yb/image/captcha.zep.h"
#include "yb/image/exception.zep.h"
#include "yb/image/gd.zep.h"
#include "yb/image/text.zep.h"
#include "yb/loader/exception.zep.h"
#include "yb/loader/namepath.zep.h"
#include "yb/loader/namespacedirectory.zep.h"
#include "yb/logger/backends.zep.h"
#include "yb/logger/exception.zep.h"
#include "yb/logger/file.zep.h"
#include "yb/logger/nil.zep.h"
#include "yb/std.zep.h"
#include "yb/task/exception.zep.h"
#include "yb/task/queueredis.zep.h"
#include "yb/task/rundirectly.zep.h"
#include "yb/task/taskexecutorinterface.zep.h"
#include "yb/upload/exception.zep.h"
#include "yb/upload/filesystem.zep.h"
#include "yb/upload/uploadedfile.zep.h"
#include "yb/upload/uploader.zep.h"
#include "yb/view/content.zep.h"
#include "yb/view/exception.zep.h"
#include "yb/view/facade.zep.h"
#include "yb/view/httpresponse.zep.h"
#include "yb/view/json.zep.h"
#include "yb/view/nil.zep.h"
#include "yb/view/readfile.zep.h"
#include "yb/view/redirect.zep.h"
#include "yb/view/tpl.zep.h"

#endif