
/* This file was generated automatically by Zephir do not modify it! */

#ifndef ZEPHIR_CLASS_ENTRIES_H
#define ZEPHIR_CLASS_ENTRIES_H

#include "yb/exception.zep.h"
#include "yb/collection/collectioninterface.zep.h"
#include "yb/factory/factoryinterface.zep.h"
#include "yb/image/imageabstract.zep.h"
#include "yb/serializer/serializerinterface.zep.h"
#include "yb/factory/classname.zep.h"
#include "yb/image/imagebackendabstract.zep.h"
#include "yb/loader/loaderabstract.zep.h"
#include "yb/application/applicationfilterinterface.zep.h"
#include "yb/application/routerabstract.zep.h"
#include "yb/collection/redishash.zep.h"
#include "yb/image/image.zep.h"
#include "yb/application/config.zep.h"
#include "yb/application/core.zep.h"
#include "yb/application/exception.zep.h"
#include "yb/application/modulerouter.zep.h"
#include "yb/application/routeruri.zep.h"
#include "yb/collection/exception.zep.h"
#include "yb/collection/mongocollection.zep.h"
#include "yb/collection/redishashserialized.zep.h"
#include "yb/factory/exception.zep.h"
#include "yb/factory/generated.zep.h"
#include "yb/factory/namespaced.zep.h"
#include "yb/image/captcha.zep.h"
#include "yb/image/exception.zep.h"
#include "yb/image/gd.zep.h"
#include "yb/image/imagick.zep.h"
#include "yb/image/text.zep.h"
#include "yb/loader/classpath.zep.h"
#include "yb/loader/exception.zep.h"
#include "yb/loader/namespacedirectory.zep.h"
#include "yb/serializer/exception.zep.h"
#include "yb/serializer/igbinary.zep.h"
#include "yb/serializer/json.zep.h"
#include "yb/serializer/php.zep.h"
#include "yb/std.zep.h"
#include "yb/tools/exception.zep.h"
#include "yb/tools/smtpmailer.zep.h"

#endif